# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qf9VQlyyhXuNOWH1URcqa1LInwUUS7Nt
"""

!pip install spacy

!python -m spacy download en_core_web_sm

import spacy
# Load the English language model
nlp = spacy.load("en_core_web_sm")

# Example text
text = "Apple is looking at buying U.K. startup for $1 billion."

#process the text
doc = nlp(text)

doc

# Text summerization

import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("data science ai and gen ai has great career ahead")

doc

for token in doc:
  print(token.text)

doc

for token in doc:
  print(token.pos_)

for token in doc:
  print(token.text,':',token.pos_,'-->',token.lemma_,token.dep_)

doc

for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
            token.shape_, token.is_alpha, token.is_stop)

import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("Apple is looking at buying U.K. startup for $1 billion")

for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
            token.shape_, token.is_alpha, token.is_stop)

text = """There are broadly two types of extractive summarization tasks depending on what the summarization program focuses on. The first is generic summarization, which focuses on obtaining a generic summary or abstract of the collection (whether documents, or sets of images, or videos, news stories etc.). The second is query relevant summarization, sometimes called query-based summarization, which summarizes objects specific to a query. Summarization systems are able to create both query relevant text summaries and generic machine-generated summaries depending on what the user needs.
An example of a summarization problem is document summarization, which attempts to automatically produce an abstract from a given document. Sometimes one might be interested in generating a summary from a single source document, while others can use multiple source documents (for example, a cluster of articles on the same topic). This problem is called multi-document summarization. A related application is summarizing news articles. Imagine a system, which automatically pulls together news articles on a given topic (from the web), and concisely represents the latest news as a summary.
Image collection summarization is another application example of automatic summarization. It consists in selecting a representative set of images from a larger set of images.[4] A summary in this context is useful to show the most representative images of results in an image collection exploration system. Video summarization is a related domain, where the system automatically creates a trailer of a long video. This also has applications in consumer or personal videos, where one might want to skip the boring or repetitive actions. Similarly, in surveillance videos, one would want to extract important and suspicious activity, while ignoring all the boring and redundant frames captured """

text

import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from string import punctuation

stopwords = list(STOP_WORDS)
stopwords

len(stopwords)

nlp = spacy.load('en_core_web_sm')

text

doc = nlp(text)
doc

# lets get the tokens from text
tokens = [token.text for token in doc]
print(tokens)
#when we execute everythihg we created tokens from the text & not removed any of the stopwords & didnt cleaned the data

#we have to calcualte the freaquency of each and every word, how many time word is repetation in text

word_frequencies = {}

for word in doc:
    if word.text.lower() not in stopwords:
        if word.text.lower() not in punctuation:
            if word.text not in word_frequencies.keys():
                word_frequencies[word.text] = 1
            else:
                word_frequencies[word.text] += 1

word_frequencies
#print(word_frequencies)

len(word_frequencies)

word_frequencies

max_frequency = max(word_frequencies.values())
max_frequency

#to get normalized/weighted frequencies you should devide all frequencies with 11
for word in word_frequencies.keys():
    word_frequencies[word] = word_frequencies[word]/max_frequency

#print(word_frequencies)
word_frequencies
#this is the normalized frequencies of each word

sentence_tokens = [sent for sent in doc.sents]
sentence_tokens

len(sentence_tokens)

sentence_tokens

# we are going to calculate the sentence score, to calculate the sentence score
sentence_scores = {}

for sent in sentence_tokens:
    for word in sent:
        if word.text.lower() in word_frequencies.keys():
            if sent not in sentence_scores.keys():
                sentence_scores[sent] = word_frequencies[word.text.lower()]
            else:
                sentence_scores[sent] += word_frequencies[word.text.lower()]

sentence_scores

len(sentence_scores)

#lets say our case study was 30% sentence with maximum scores
from heapq import nlargest

select_length = int(len(sentence_tokens)*0.4)
select_length

#we have to select maximum 40 sentences out of all sentences
summary = nlargest(select_length,sentence_scores, key = sentence_scores.get)

summary

# if i need to combine these top 3 sentencs then

final_summary = [word.text for word in summary]

final_summary